config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/upmin'

  devise_for :users

  root "reservations#index"

  resources :console_servers
  resources :reservations
  resources :topologies
  resources :devices
  resources :mrvs
  resources :credentials
end

app/models/mrv.rb
class Mrv < ActiveRecord::Base
  has_one :ipv4_address, as: :ipv4_addressable, dependent: :destroy
  has_many :mrv_interfaces, dependent: :destroy

  validates :name, uniqueness: true

  accepts_nested_attributes_for :ipv4_address, :allow_destroy => true
  accepts_nested_attributes_for :mrv_interfaces, :allow_destroy => true
end

app/controllers/mrvs_controller.rb
class MrvsController < ApplicationController
  before_action :set_mrv, only: [:show, :edit, :update, :destroy]

  # GET /mrvs
  # GET /mrvs.json
  def index
    @mrvs = Mrv.all
  end

  # GET /mrvs/1
  # GET /mrvs/1.json
  def show
  end

  # GET /mrvs/new
  def new
    @mrv = Mrv.new
  end

  # GET /mrvs/1/edit
  def edit
  end

  # POST /mrvs
  # POST /mrvs.json
  def create
    @mrv = Mrv.new(mrv_params)

    respond_to do |format|
      if @mrv.save
        format.html { redirect_to @mrv, notice: 'Mrv was successfully created.' }
        format.json { render :show, status: :created, location: @mrv }
      else
        format.html { render :new }
        format.json { render json: @mrv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mrvs/1
  # PATCH/PUT /mrvs/1.json
  def update
    respond_to do |format|
      if @mrv.update(mrv_params)
        format.html { redirect_to @mrv, notice: 'Mrv was successfully updated.' }
        format.json { render :show, status: :ok, location: @mrv }
      else
        format.html { render :edit }
        format.json { render json: @mrv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mrvs/1
  # DELETE /mrvs/1.json
  def destroy
    @mrv.destroy
    respond_to do |format|
      format.html { redirect_to mrvs_url, notice: 'Mrv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mrv
      @mrv = Mrv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mrv_params
      params.require(:mrv).permit(:name, :description, :credential_id, :ipv4_address_attributes => [:address])
    end
end

app/helpers/mrvs_helper.rb
module MrvsHelper
end

app/views/mrvs/_form.html.haml
= form_for @mrv do |f|
  - if @mrv.errors.any?
    #error_explanation
      %h2= "#{pluralize(@mrv.errors.count, "error")} prohibited this mrv from being saved:"
      %ul
        - @mrv.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  -#.field
    = f.label :ipv4_address
    = f.text_field :ipv4_address
  .field
    = f.label :credential_id
    = collection_select(:console_server, :credential_id, Credential.all, :id, :name)

  .actions
    = f.submit 'Save'

app/views/mrvs/edit.html.haml
%h1 Editing mrv

= render 'form'

= link_to 'Show', @mrv
\|
= link_to 'Back', mrvs_path

app/views/mrvs/index.html.haml
%h1 Listing MRVs

%table
  %tr
    %th Name
    %th IP Address
    %th
    %th
    %th

  - @mrvs.each do |mrv|
    %tr
      %td= mrv.name
      %td ip address
      %td= link_to 'Show', mrv
      %td= link_to 'Edit', edit_mrv_path(mrv)
      %td= link_to 'Destroy', mrv, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Mrv', new_mrv_path

app/views/mrvs/new.html.haml
%h1 New mrv

= render 'form'

= link_to 'Back', mrvs_path

app/views/mrvs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @mrv.name
%p
  %b Description:
  = @mrv.description
%p
  %b Credential ID:
  = @mrv.credential_id

= link_to 'Edit', edit_mrv_path(@mrv)
\|
= link_to 'Back', mrvs_path