config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/upmin'

  devise_for :users

  root "reservations#index"

  resources :console_servers
  resources :reservations
  resources :topologies
  resources :devices
  resources :mrvs
  resources :credentials
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :credential

  has_many :ipv4_addresses, as: :ipv4_addressable, dependent: :destroy
  has_many :device_interfaces, dependent: :destroy
  has_many :device_console_interfaces, dependent: :destroy
  has_many :saved_configurations, dependent: :destroy

  validates :name, uniqueness: true

  accepts_nested_attributes_for :ipv4_addresses, :allow_destroy => true
  accepts_nested_attributes_for :device_interfaces, :allow_destroy => true
  accepts_nested_attributes_for :device_console_interfaces, :allow_destroy => true
  accepts_nested_attributes_for :saved_configurations, :allow_destroy => true
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :description, :base_configuration, :credential_id, :ipv4_addresses_attributes => [:address])
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  - if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  -#.field
    = f.label :ipv4_address
    = f.text_field :ipv4_address
  .field
    = f.label :credential_id
    = collection_select(:device, :credential_id, Credential.all, :id, :name)
  .field
    = f.label :base_configuration
    = f.text_area :base_configuration
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %tr
    %th Name
    %th IP Address
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td= device.name
      %td  IP Address
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @device.name
%p
  %b Description:
  = @device.description
%p
  %b Base Configuration:
  = @device.base_configuration
%p
  %b Credential ID
  = @device.credential_id

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path