config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/upmin'

  devise_for :users

  root "reservations#index"

  resources :console_servers
  resources :reservations
  resources :topologies
  resources :devices
  resources :mrvs
  resources :credentials
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user

  belongs_to :topology
  
  has_many :saved_configurations, dependent: :destroy

  validates :name, uniqueness: true
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true

  accepts_nested_attributes_for :saved_configurations, :allow_destroy => true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    reservations = Reservation.all
    @page = {:reservations => reservations}
  end

  def new
    user = User.find_by_id(current_user.id)
    topologies = Topology.all
    reservation = user.reservations.build
    @page = {:reservation => reservation, :user => user, :topologies => topologies}
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_index_table.html.haml
.rs-page-title Reservations
.rs-btn-group
  %a= link_to 'New Reservation', new_reservation_path, class: 'rs-btn rs-btn-primary'
  %input{type: 'search', class: 'rs-input-large rs-pull-right reservation-search', placeholder: 'Search Reservations'}
%table.rs-list-table
  %thead
    %tr
      %th.rs-table-cog
      %th.rs-table-sort
        %span.rs-table-sort-text Name
      %th.rs-table-sort
        %span.rs-table-sort-text Topology
      %th.rs-table-sort
        %span.rs-table-sort-text User
      %th.rs-table-sort
        %span.rs-table-sort-text Start Time
      %th.rs-table-sort
        %span.rs-table-sort-text End Time
  %tbody.reservation-table
    - @page[:reservations].each do |reservation|
      %tr
        %td.rs-table-cog
          .rs-dropdown
            .rs-cog.rs-dropdown-toggle
            %ul.rs-dropdown-menu.hidden
              %li
                %span.rs-dropdown-category Do Things
              %li
                %a= link_to 'Edit', edit_reservation_path(reservation.id)
              %li
                %a= link_to 'Destroy', reservation_path(reservation.id), method: :delete
        %td= link_to reservation.name, reservation_path(reservation.id)
        %td= link_to reservation.topology.name, topology_url(reservation.topology.id)
        %td= reservation.user.ldap_name
        %td= reservation.start_datetime
        %td= reservation.end_datetime

app/views/reservations/_index_table_none_yet.html.haml
.rs-page-title Reservations
.rs-btn-group
  %a= link_to 'New Reservation', new_reservation_path, class: "rs-btn rs-btn-primary"
  %input{type: 'text', class: 'rs-input-large rs-pull-right', placeholder: 'Search Reservations'}
%table.rs-list-table
  %thead
    %tr
      %th.rs-table-cog
      %th.rs-table-sort
        %span.rs-table-sort-text Name
      %th.rs-table-sort
        %span.rs-table-sort-text Topology
      %th.rs-table-sort
        %span.rs-table-sort-text User
      %th.rs-table-sort
        %span.rs-table-sort-text Start Time
      %th.rs-table-sort
        %span.rs-table-sort-text End Time
  %tbody
.rs-table-overlay
  .rs-table-overlay-content
    .rs-table-overlay-title There are no Reservations yet. :c
    .rs-table-overlay-subtitle
      Make one
      %a{href: new_reservation_path}
        Now!
        %i.rs-icon-external

app/views/reservations/index.html.haml
.rs-content.rs-panel
  .rs-inner
    - if @page[:reservations].any?
      = render('index_table')
    - else
      = render('index_table_none_yet')
:javascript
  $(document).ready(function () {
      (function ($) {
          $('.reservation-search').keyup(function () {
              var rex = new RegExp($(this).val(), 'i');
              $('.reservation-table tr').hide();
              $('.reservation-table tr').filter(function () {
                  return rex.test($(this).text());
              }).show();
          })
      }(jQuery));
  });

app/views/reservations/index_none_yet.html.haml
.rs-page-title Reservations
.rs-btn-group
  %a= link_to 'New Reservation', new_reservation_path, class: "rs-btn rs-btn-primary"
  %input{type: 'text', class: 'rs-input-large rs-pull-right', placeholder: 'Search Reservations'}
%table.rs-list-table
  %thead
    %tr
      %th.rs-table-cog
      %th.rs-table-sort
        %span.rs-table-sort-text Name
      %th.rs-table-sort
        %span.rs-table-sort-text Topology
      %th.rs-table-sort
        %span.rs-table-sort-text User
      %th.rs-table-sort
        %span.rs-table-sort-text Start Time
      %th.rs-table-sort
        %span.rs-table-sort-text End Time
  %tbody
.rs-table-overlay
  .rs-table-overlay-content
    .rs-table-overlay-title There are no Reservations yet. :c
    .rs-table-overlay-subtitle
      Make one
      %a{href: new_reservation_path}
        Now!
        %i.rs-icon-external

app/views/reservations/new.html.haml
= stylesheet_link_tag 'new_reservation'
// override bootstrap tables yo
%link{href: "https://eafdbc63c97ce6bec9ef-b0a668e5876bef6fe25684caf71db405.ssl.cf1.rackcdn.com/v1-latest//canon.min.css", rel: "stylesheet", type: "text/css"}
.rs-content.rs-panel
  = form_for(@page[:reservation], :html => {:class => 'rs-form-create'}) do |f|
    .rs-detail-section
      .rs-detail-section-header
        %h2.rs-page-title
          Create a Lab Reservation
        .rs-detail-section-title
          Reservation Details
      .rs-detail-section-body
        .rs-control-group
          .rs-control-label Reservation Name
          .rs-controls
            = f.text_field :name, :class => 'rs-input-large'
        .rs-control-group
          .rs-control-label Reservation Description
          .rs-controls
            = f.text_field :description, :class => 'rs-input-large'
        .rs-control-group
          .rs-control-label Start Time
          .rs-controls
            = f.text_field :start_datetime, class: 'start-input'
        .rs-control-group
          .rs-control-label End Time
          .rs-controls
            = f.text_field :end_datetime, class: 'end-input'
    .rs-detail-section
      .rs-detail-section-header
        .rs-detail-section-title
          Select a Topology
      .rs-detail-section-body
        .rs-btn-group
          %input{type: 'text', class: 'rs-input-large rs-pull-right topology-search', placeholder: 'Search Topologies'}
        .rs-embedded-list-table-wrapper.rs-embedded-large
          %table.rs-list-table.rs-embedded-list-table
            %thead
              %tr
                %th.rs-table-radio
                %th
                  %a.rs-table-sort
                    %span.rs-table-sort-text Name
                %th.rs-table-sort
                  %span.rs-table-sort-text Description
            %tbody.phtt-table
              - @page[:topologies].each do |topology|
                %tr
                  %td.rs-table-radio
                    %input{type: 'radio', name: 'topology_id', value: topology.id}
                  %td= link_to topology.name, topologies_path(topology.id)
                  %td= topology.description
    .rs-detail-section
      .rs-detail-section-header.rs-btn-group
        = f.submit 'Create Reservation', class: 'rs-btn rs-btn-primary'
        %a.rs-btn.rs-btn-link= link_to 'Cancel', reservations_path
:javascript
  $(document).ready(function () {
      (function ($) {
          $('.topology-search').keyup(function () {
              var rex = new RegExp($(this).val(), 'i');
              $('.phtt-table tr').hide();
              $('.phtt-table tr').filter(function () {
                  return rex.test($(this).text());
              }).show();
          })
      }(jQuery));
  });
= javascript_include_tag 'new_reservation'