config/routes.rb
Rails.application.routes.draw do
  mount Upmin::Engine => '/upmin'

  devise_for :users

  root "reservations#index"

  resources :console_servers
  resources :reservations
  resources :topologies
  resources :devices
  resources :mrvs
  resources :credentials
end

app/models/credential.rb
class Credential < ActiveRecord::Base
  has_many :devices, dependent: :nullify
  has_many :console_servers, dependent: :nullify
  has_many :mrvs, dependent: :nullify

  validates :name, uniqueness: true, presence: true
  validates :username, presence: true
  validates :password, presence: true
end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_action :set_credential, only: [:show, :edit, :update, :destroy]

  # GET /credentials
  # GET /credentials.json
  def index
    @credentials = Credential.all
  end

  # GET /credentials/1
  # GET /credentials/1.json
  def show
  end

  # GET /credentials/new
  def new
    @credential = Credential.new
  end

  # GET /credentials/1/edit
  def edit
  end

  # POST /credentials
  # POST /credentials.json
  def create
    @credential = Credential.new(credential_params)

    respond_to do |format|
      if @credential.save
        format.html { redirect_to @credential, notice: 'Credential was successfully created.' }
        format.json { render :show, status: :created, location: @credential }
      else
        format.html { render :new }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credentials/1
  # PATCH/PUT /credentials/1.json
  def update
    respond_to do |format|
      if @credential.update(credential_params)
        format.html { redirect_to @credential, notice: 'Credential was successfully updated.' }
        format.json { render :show, status: :ok, location: @credential }
      else
        format.html { render :edit }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1
  # DELETE /credentials/1.json
  def destroy
    @credential.destroy
    respond_to do |format|
      format.html { redirect_to credentials_url, notice: 'Credential was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credential
      @credential = Credential.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credential_params
      params.require(:credential).permit(:name, :description, :username, :password, :enable_password)
    end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_form.html.haml
= form_for @credential do |f|
  - if @credential.errors.any?
    #error_explanation
      %h2= "#{pluralize(@credential.errors.count, "error")} prohibited this credential from being saved:"
      %ul
        - @credential.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :enable_password
    = f.text_field :enable_password
  .actions
    = f.submit 'Save'

app/views/credentials/edit.html.haml
%h1 Editing credential

= render 'form'

= link_to 'Show', @credential
\|
= link_to 'Back', credentials_path

app/views/credentials/index.html.haml
%h1 Listing credentials

%table
  %tr
    %th Name
    %th Username
    %th
    %th
    %th

  - @credentials.each do |credential|
    %tr
      %td= credential.name
      %td= credential.username
      %td= link_to 'Show', credential
      %td= link_to 'Edit', edit_credential_path(credential)
      %td= link_to 'Destroy', credential, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Credential', new_credential_path

app/views/credentials/new.html.haml
%h1 New credential

= render 'form'

= link_to 'Back', credentials_path

app/views/credentials/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @credential.name
%p
  %b Description:
  = @credential.description
%p
  %b Username:
  = @credential.username
%p
  %b Password:
  = @credential.password
%p
  %b Enable Password:
  = @credential.enable_password

= link_to 'Edit', edit_credential_path(@credential)
\|
= link_to 'Back', credentials_path